### ISSUE TITLE
Suggestion: Mention the use of #!/usr/bin/env c to launch script.

### ISSUE THREAD

**Issue by nashidau** [ryanmjacobs/c#5]
#!/usr/bin/env c
At the top of the script searches your path for 'c' and execute that script.

Means you can use it no matter where your 'c' is installed (~/bin/ /usr/local/bin or /usr/bin et al).

**Comment by jwerle** [comment]
+1

**Comment by jasonkeene** [comment]
+1

**Comment by ryanmjacobs** [comment]
I wish this portable. I originally was going to use `env`, but had to settle on direct paths because Linux doesn't support multiple arguments with `#!`.

On Linux systems, `#!` "splits at the first whitespace and treats the front part as the path to the interpeter and the rest as a single argument." On BSD systems, `#!` "splits at whitespace and treats the first part as the path to the interpreter and the rest as individual arguments."

http://stackoverflow.com/a/4304187/2002146

On most systems `#!/usr/bin/env c` works fine. It's only when you start adding additional arguments to `c` that it fails, e.g. `#!/usr/bin/env c -lncurses -Wall --`.
